# Generated by Django 4.2.5 on 2023-09-16 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='acccount_id',
            new_name='account_id',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='acccount_number',
            new_name='account_number',
        ),
    ]
