# Generated by Django 4.2.5 on 2023-10-23 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_kyc_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='deleted_account',
            field=models.BooleanField(default=False),
        ),
    ]
