# Generated by Django 4.2.5 on 2023-10-25 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_account_deleted_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='kyc',
            name='is_mobile_verfied',
            field=models.BooleanField(default=False),
        ),
    ]
