# Generated by Django 4.2.5 on 2023-10-25 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_2fa',
            field=models.BooleanField(default=False),
        ),
        
    ]
