# Generated by Django 4.2.5 on 2023-10-25 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0005_user_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='uid',
        ),
    ]
