# Generated by Django 4.2.5 on 2023-10-17 05:31

from django.db import migrations
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_creditcard_card_pin_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='cvv',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=3, max_length=3, prefix=''),
        ),
    ]
