# Generated by Django 4.2.5 on 2023-10-17 05:39

from django.db import migrations, models
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_creditcard_cvv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='month',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='number',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=16, max_length=16, prefix='47'),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='year',
            field=models.IntegerField(default=2028),
        ),
    ]
