# Generated by Django 4.2.5 on 2023-10-17 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_creditcard_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creditcard',
            old_name='card_id',
            new_name='credit_card_id',
        ),
    ]
