# Generated by Django 4.2.5 on 2023-10-19 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_reciever_notification_receiver'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='card_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='card_tier',
            field=models.CharField(choices=[('classic', 'Classic'), ('gold', 'Gold'), ('platinum', 'Platinum'), ('signature', 'Signature'), ('infinite', 'Infinite')], default='classic', max_length=20),
        ),
        migrations.AddField(
            model_name='notification',
            name='card_type',
            field=models.CharField(choices=[('master', 'Master'), ('visa', 'Visa'), ('rupay', 'Rupay')], default='master', max_length=20),
        ),
    ]
