# Generated by Django 4.2.5 on 2023-10-19 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_notification_card_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
